### ISSUE TITLE
Sorting by % mapped read or %duplicate reads stall the app

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/Reporting-App#8]

**Comment by mwhamgenomics** [comment]
Stacktrace:

```python
ERROR:eve:Exception on /api/0.1/samples [GET]
Traceback (most recent call last):
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/eve/endpoints.py", line 63, in collections_endpoint
    return send_response(resource, response)
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/eve/render.py", line 65, in decorated
    getattr(app, event_name + '_' + resource)(request, r)
  File "/home/mwham/Applications/python/reporting/lib/python3.4/site-packages/events/events.py", line 77, in __call__
    f(*a, **kw)
  File "/home/mwham/Applications/Analysis_Driver_reporting/Reporting-App/current/rest_api/__init__.py", line 94, in embed_run_elements_into_samples
    sortquery=_from_query_string(request.args, 'sort', json=False)
  File "/home/mwham/Applications/Analysis_Driver_reporting/Reporting-App/current/rest_api/aggregation/server_side/__init__.py", line 18, in aggregate_samples
    return _order_json(input_json, sortquery)
  File "/home/mwham/Applications/Analysis_Driver_reporting/Reporting-App/current/rest_api/aggregation/server_side/__init__.py", line 58, in _order_json
    input_json['data'] = sorted(input_json['data'], key=lambda e: itemgetter(sortcol)(e), reverse=reverse)
TypeError: unorderable types: NoneType() < NoneType()
ERROR:tornado.access:500 GET /api/0.1/samples?embedded={%22run_elements%22:1}&where={%22project%22:%22X0002DM%22}&max_results=10&page=1&sort=yield_in_gb (129.215.144.184) 113.26ms
```
